
url: http://getwanderlostandfound.com
disqus_shortname: wanderlostandfound 

plugins:
  - jekyll-analytics
  - jekyll-archives

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-115008219-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

jekyll-archives:
  enabled: true
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
